version: '1'
services:
   db:
     image: mysql:8.0
     container_name: my_db
     environment:
      MYSQL_ROOT_PASSWORD: root
     ports:
      - "3306:3306"
     volumes:
      - ./mysqldata:/var/lib/mysql
   adminer:
     container_name: adminer
     image: adminer
     restart: always
     depends_on:
      - db
     ports:
      - "8080:8080"
